### ISSUE TITLE
Missing configuration key for Stripe One-off contributionsa

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/support-frontend#214]
Sample log follows:
```
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'oneOffStripe.api.key.secret'
at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
at com.gu.support.config.StripeConfigProvider.fromConfig(StripeConfig.scala:9)
at com.gu.support.config.StripeConfigProvider.fromConfig(StripeConfig.scala:7)
at com.gu.support.config.TouchpointConfigProvider.uatConfig$lzycompute(TouchpointConfigProvider.scala:16)
at com.gu.support.config.TouchpointConfigProvider.uatConfig(TouchpointConfigProvider.scala:16)
at com.gu.support.config.TouchpointConfigProvider.get(TouchpointConfigProvider.scala:19)
at controllers.OneOffContributions.controllers$OneOffContributions$$form(OneOffContributions.scala:55)
at controllers.OneOffContributions$$anonfun$displayFormTestUser$1.apply(OneOffContributions.scala:39)
at controllers.OneOffContributions$$anonfun$displayFormTestUser$1.apply(OneOffContributions.scala:39)
at play.api.mvc.ActionBuilder$$anonfun$apply$11.apply(Action.scala:363)
at play.api.mvc.ActionBuilder$$anonfun$apply$11.apply(Action.scala:363)
at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
at scala.util.Either.fold(Either.scala:99)
at play.api.mvc.ActionRefiner$$anonfun$invokeBlock$3.apply(Action.scala:522)
at play.api.mvc.ActionRefiner$$anonfun$invokeBlock$3.apply(Action.scala:522)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
```

**Comment by davidfurey** [comment]
Does this affect all environments or just DEV?

**Comment by Ap0c** [comment]
Can I close this?

**Comment by svillafe** [comment]
Should we close this issue?

**Comment by michaelwmcnamara** [comment]
Seen pretty frequently in Prod up until 02 Feb - suspect this was fixed by https://github.com/guardian/support-frontend/pull/480
